---
title: "mia rfid"
output: html_document
---

<br>

loading in packages
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

<br>

loading in data
```{r, message=FALSE}
df <- read_csv2("raw_data/Tracking/rawdata20210610.csv")
df$data <- as.character(df$data)
```

<br>

looking at `cantimestamp`
```{r}
range(df$cantimestamp)
df$time <- df$cantimestamp - min(df$cantimestamp)
df[1:10,]

plot(df$cantimestamp, type="l")
```

<br>

looking at `datetimestamp`
(1) Why are some hours not included or missing? Are mice sleeping, did filming stop? did mice escape?
```{r}
time <- sub("^\\S+\\s+", '', df$datetimestamp)
hours <- sub("\\:.*", "", time)
table(hours)
```

<br>

```{r, warning=FALSE, message=FALSE, results='hide'}
df$date <- format(as.POSIXct(df$datetimestamp,format="%m.%d.%Y %H:%M:%S:%OS"),"%m.%d.%Y")
  
df$time <- sub("^\\S+\\s+", '', df$datetimestamp)
  

xx <- strsplit(df$time, split=":")

xx
xxx <- matrix(unlist(xx), ncol = 4, byrow = TRUE)
xxx[,1]
xxx[,2]
xxx[,3]
as.numeric(xxx[,4])

df$ms<-
  (3600000 * as.numeric(xxx[,1])) +
(60000 * as.numeric(xxx[,2])) +
(1000 * as.numeric(xxx[,3])) +
(1 * as.numeric(xxx[,4]))
```
```{r}
head(df)
```

<br>

```{r, warning=FALSE, message=FALSE}
df2 <- read_csv2("raw_data/Tracking/rawdata20210604.csv")
head(df2)
```

```{r, results='hide'}

df2$date <- format(as.POSIXct(df2$datetimestamp,format="%m.%d.%Y %H:%M:%S:%OS"),"%m.%d.%Y")
  
df2$time <- sub("^\\S+\\s+", '', df2$datetimestamp)
  

xx <- strsplit(df2$time, split=":")

xx
xxx <- matrix(unlist(xx), ncol = 4, byrow = TRUE)
xxx[,1]
xxx[,2]
xxx[,3]
as.numeric(xxx[,4])

df2$ms<-
  (3600000 * as.numeric(xxx[,1])) +
(60000 * as.numeric(xxx[,2])) +
(1000 * as.numeric(xxx[,3])) +
(1 * as.numeric(xxx[,4]))

df$ms <- df$ms * 8.64e+7 * 6
df$ms <- as.character(df$ms - 40089792)
```

<br>

```{r}

tube_errors <- function(df, pair1=c(1,2), pair2=c(3,4)){
  
  ids <- c(pair1,pair2)
  codes <- c("3","19", "17", "9")
  
  x <- codes[match(df$deviceid, ids)]
  
  row.inds <-
    c(intersect(which(x == "3"),which(lead(x) == "19" | lag(x) == "19")),
      intersect(which(x == "17"),which(lead(x) == "9" | lag(x) == "9"))
       )
  
  df$error <- FALSE
  df[row.inds,"error"]<-TRUE
  
  return(df)
  }

df <- as.data.frame(tube_errors(df, pair1 = c(3,19), pair2 = c(17,9)))

filter(df, error==TRUE)

## return row numbers coming from original
```


Look into NAs







