---
title: "mia-rfid"
output:
  html_document: default
  pdf_document: default
---

loading in packages
```{r, warning=FALSE, message=FALSE, results='hide'}
library(tidyverse)

```

loading in data
```{r, warning=FALSE, message=FALSE, results='hide'}
df1 <- read_csv2("raw_data/Tracking/rawdata20210604.csv")
df2 <- read_csv2("raw_data/Tracking/rawdata20210605.csv")
df3 <- read_csv2("raw_data/Tracking/rawdata20210606.csv")
df4 <- read_csv2("raw_data/Tracking/rawdata20210607.csv")
df5 <- read_csv2("raw_data/Tracking/rawdata20210608.csv")
df6 <- read_csv2("raw_data/Tracking/rawdata20210609.csv")
df7 <- read_csv2("raw_data/Tracking/rawdata20210610.csv")
```

stacking the data together
```{r, warning=FALSE, message=FALSE, results='hide'}
df <- rbind(df1, df2, df3, df4, df5, df6, df7)

df$data <- as.character(df$data)

df
```

creating milliseconds (ms) column
```{r, warning=FALSE, message=FALSE, results='hide'}
df$date <- format(as.POSIXct(df$datetimestamp,format="%d.%m.%Y %H:%M:%S:%OS"),"%m.%d.%Y")
  
df$time <- sub("^\\S+\\s+", '', df$datetimestamp)

xx <- strsplit(df$time, split=":")

#xx
xxx <- matrix(unlist(xx), ncol = 4, byrow = TRUE)
#xxx[,1]
#xxx[,2]
#xxx[,3]
#as.numeric(xxx[,4])

df$ms<-
  (3600000 * as.numeric(xxx[,1])) +
(60000 * as.numeric(xxx[,2])) +
(1000 * as.numeric(xxx[,3])) +
(1 * as.numeric(xxx[,4]))
```

editing ms column to account for number days past
```{r, warning=FALSE, message=FALSE, results='hide'}
day_1 <- df %>% filter(date == "06.04.2021")

  day_1$ms <- as.numeric(unlist(day_1$ms)) - 40089792

day_2 <- df %>% filter(date == "06.05.2021")

  day_2$ms <- (as.numeric(unlist(day_2$ms)) + (8.64e+7 * 1)) - 40089792

day_3 <- df %>% filter(date == "06.06.2021")

  day_3$ms <- (as.numeric(unlist(day_3$ms)) + (8.64e+7 * 2)) - 40089792

day_4 <- df %>% filter(date == "06.07.2021")

  day_4$ms <- (as.numeric(unlist(day_4$ms)) + (8.64e+7 * 3)) - 40089792

day_5 <- df %>% filter(date == "06.08.2021")

  day_5$ms <- (as.numeric(unlist(day_5$ms)) + (8.64e+7 * 4)) - 40089792
  
day_6 <- df %>% filter(date == "06.09.2021")

  day_6$ms <- (as.numeric(unlist(day_6$ms)) + (8.64e+7 * 5)) - 40089792

day_7 <- df %>% filter(date == "06.10.2021")

  day_7$ms <- (as.numeric(unlist(day_7$ms)) + (8.64e+7 * 6)) - 40089792

df <- rbind(day_1, day_2, day_3, day_4, day_5, day_6, day_7)

df$ms <- as.character(df$ms)

as.data.frame(df[37200:37300, ])
```

comparing `cantimestamp` with `milliseconds`
```{r}
plot(df$cantimestamp, type = "l")
plot(df$ms, type = "l")

```
```{r}
head(df)
df %>% 
  group_by(date) %>%
  arrange(ms) %>%
  mutate(rowid=row_number()) %>%
  ggplot(., aes(x=rowid, y=cantimestamp)) +
  geom_line() +
  facet_wrap(~date)
```

comparing cantimestamp restarting points to ms
```{r}
which(lead(df$cantimestamp)<df$cantimestamp) + 1 

drops <- df$ms[which(lead(df$cantimestamp)<df$cantimestamp) + 1 ]

drops <- as.data.frame(as.numeric(drops))
colnames(drops) <- c("delta_drops")

drops <- tail(drops, -1) - head(drops, -1)

table(drops)

hist(drops$delta_drops)

hist(df$cantimestamp)
```

making a function to report impossible tube connections
```{r, warning=FALSE, message=FALSE, results='hide'}
tube_errors <- function(df, pair1=c(1,2), pair2=c(3,4)){
  
  ids <- c(pair1,pair2)
  codes <- c("3","19", "17", "9")
  
  x <- codes[match(df$deviceid, ids)]
  
  row.inds <-
    c(intersect(which(x == "3"),which(lead(x) == "19" | lag(x) == "19")),
      intersect(which(x == "17"),which(lead(x) == "9" | lag(x) == "9"))
       )
  
  df$error <- FALSE
  df[row.inds,"error"]<-TRUE
  
  return(df)
  }

df <- as.data.frame(tube_errors(df, pair1 = c(3,19), pair2 = c(17,9)))

filter(df, error==TRUE)

```

dealing with NAs
```{r}
df$row <- 1:nrow(df)

dd <- df %>%
  arrange(ms)
z <- dd == df
sum(z[,1] == FALSE)

df$ms <- as.integer(df$ms)

Match <- function(row) {
  subset(df, deviceid == df$deviceid & 
                antennaID == df$antennaID &
                row > df$row &
                is.na(data))[1, "row"]
  }

f <- function(x) df[c(sapply(1:nrow(x), function(i) c(x$row[i], Match(x[i, ])))), ]

ddf <- lapply(split(df, df$data), f)
```

```{r}
m4_1 <- ddf[["900133000459724"]]
m4_2 <- ddf[["900133000459725"]]
m4 <- (m4_1, m4_2, 'ms') ???

m3_1 <- ddf[["900133000459723"]]
m3_2 <- ddf[["900133000459727"]]
m3 <- 
  
m2_1 <- ddf[["900133000459721"]]
m2_2 <- ddf[["900133000459722"]] 
m2 <- 
  
m1_1 <- ddf[["900133000459719"]] 
m1_2 <- ddf[["900133000459693"]]
m1 <- 

```






